cmake_minimum_required(VERSION 3.26.5)
project(cs-primer C)

set(CMAKE_C_STANDARD 23)
set(CMAKE_VERBOSE_MAKEFILE ON)

#add_subdirectory(01-programming-beyond-the-basics)
#add_subdirectory(02-computer-systems)
#add_subdirectory(03-algorithms-and-data-structures)
add_subdirectory(04-computer-networks)
#add_subdirectory(05-operating-systems)
#add_subdirectory(06-relational-databases)
